name: Release CI

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
      - name: 获取静态资源
        run: make fetch
      - name: 安装 Rust 工具链
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: "x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl"
      - name: 构建 chai
        run: |
          cargo build --target x86_64-unknown-linux-gnu --bin chai --release
          cargo build --target x86_64-unknown-linux-musl --bin chai --release
      - name: Archive
        run: |
          cp target/x86_64-unknown-linux-gnu/release/chai ./
          tar -czf chai-linux-gnu.tar.gz chai assets/* examples/* README.md LICENSE
          cp target/x86_64-unknown-linux-musl/release/chai ./
          tar -czf chai-linux-musl.tar.gz chai assets/* examples/* README.md LICENSE
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: false
          includeInvalidCommits: true
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "chai*.tar.gz"
          allowUpdates: true
          body: |
            ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
      - name: 获取静态资源
        run: make fetch
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Install Rust Toolchains
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: "x86_64-apple-darwin, aarch64-apple-darwin"
      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild
      - name: Build
        run: cargo zigbuild --target universal2-apple-darwin --bin chai --release
      - name: Archive
        run: |
          cp target/universal2-apple-darwin/release/chai ./
          tar -czf chai-macos.tar.gz chai assets/* examples/* README.md LICENSE
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: false
          includeInvalidCommits: true
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "chai-macos.tar.gz"
          allowUpdates: true
          body: |
            ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
      - name: 获取静态资源
        run: |
          choco install curl
          make fetch
      - name: Install Rust Toolchains
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: "x86_64-pc-windows-msvc"
      - name: Build
        run: cargo build --bin chai --release
      - name: Archive
        run: |
          cp target/release/chai.exe ./
          7z a -tzip chai-windows.zip chai.exe assets/* examples/* README.md LICENSE
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: false
          includeInvalidCommits: true
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "chai-windows.zip"
          allowUpdates: true
          body: |
            ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}
